St-Jo'Studio Display - Initialisation...
Chargement des données depuis Google Sheets...
Date du jour (today): Mon Nov 04 2025 00:00:00 GMT...

--- Ligne 2 du Google Sheet ---
Valeur brute startDate: 02/11/2025  (ou un nombre comme 45597)
Valeur brute endDate: 05/11/2025
📅 Parsing date: 02/11/2025 | Type: string
✅ Date from DD/MM/YYYY: Sat Nov 02 2025...
Après parsing - startDate: Sat Nov 02 2025...
Après parsing - endDate: Tue Nov 05 2025...
Guest: Martine Guillaum | Status: Confirmé
Comparaison: startDate <= today ? true
Comparaison: endDate >= today ? true
Comparaison: status confirmé ? true
✅ RÉSERVATION EN COURS TROUVÉE: Martine Guillaum

=== RÉSULTAT FINAL ===
Réservation actuelle: {guestName: "Martine Guillaum", ...}
